# Generated by Django 2.2.6 on 2019-11-17 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('titulo', models.CharField(max_length=30)),
                ('cor', models.CharField(max_length=15)),
                ('data_inicio', models.CharField(blank=True, max_length=100, null=True)),
                ('data_fim', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substancias', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoFarmaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substancia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoFarmacoII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substancia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intensidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cientifico', models.CharField(max_length=50)),
                ('efeito', models.TextField(max_length=200)),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Classificacao')),
                ('farmacos', models.ManyToManyField(to='core.Farmaco')),
                ('grupo_farmacoI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GrupoFarmaco')),
                ('grupo_farmacoII', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GrupoFarmacoII')),
                ('intensidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Intensidade')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Remedio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Remedio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
