# Generated by Django 2.2.6 on 2019-11-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analise',
            name='remedio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='analise',
            name='usuario',
            field=models.IntegerField(),
        ),
    ]
