# Generated by Django 2.2.6 on 2019-11-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191117_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='remedio',
        ),
        migrations.AddField(
            model_name='historico',
            name='remedio',
            field=models.ManyToManyField(to='core.Remedio'),
        ),
    ]
