# Generated by Django 2.2.6 on 2019-11-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191117_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='remedio',
        ),
        migrations.AddField(
            model_name='historico',
            name='remedio',
            field=models.CharField(default=0.0007654554459903643, max_length=50),
            preserve_default=False,
        ),
    ]
